### ISSUE TITLE
File Watcher - Local Static Files

### ISSUE THREAD

**Issue by jpuerto-psc** [MaayanLab/appyter#137]
Hello All,

I am in the process of testing out Appyter and was curious about how the file watching is controlled/managed. I understand that there are four directories that are "watched" as part of the development instantiation. However, I believe that this particular watch block is causing issues:

https://github.com/MaayanLab/appyter/blob/f63630ecad857903473dd9596effde6eb78cb449/appyter/render/flask_app/development.py#L120-L127

This block is watching **all** files in the CWD that are not in the data_dir or python files. This is causing issues as we have some log files which are populated during the time that Appyter starts up and is running. This log files are triggering reloads, which trigger more logs to be generated by `file_watcher`, triggering more reloads.

If this block is meant to watch the local static files (`--static-dir`) would it be possible to switch this block to watch that? Happy to put in a PR to do this work.

Another option would be to have a flag that turns off file_watching entirely.

Best regards,

Juan

**Comment by u8sand** [comment]
Hi @jpuerto-psc , --debug=false would disable watching but also change how things are served. When developing an appyter watching is extremely useful. The reason the current directory is watched is because besides the `static-dir` there are also several other directories or supplemental files which could have an affect on the running appyter (https://github.com/MaayanLab/appyter/tree/main/example has a rather elaborate example showcasing many different features).

My suggestion for now might might be to store the logs in a parent directory perhaps, (`--cwd` can be configured via the command line)

**Comment by jpuerto-psc** [comment]
@u8sand - thank you for these details. Yes, I did try to set the debug flag to false, but (unfortunately) this won't work for us as this requires us to install Nginx on any compute/GPU node where we might have Appyter run.

The way that we would run these Appyter instances would require that the logs be stored in a child directory of where we point `--cwd`. Following is an example of how we have the directories configured when running Appyter as part of a particular invocation:

appyter_root_directory
 - appyter.ipynb
 - .hidden_directory_where_log_files_are_stored
 - .hidden_virtual_environment_for_appyter
 - miscellaneous_directories_with_additional_data

I completely understand the value in having the development invocation having some level of file watching, but being able to control that (or turn it off entirely) based on a flag would be helpful. As I mentioned, we have to invoke Appyter in this way because of our limitation with Nginx, but I understand that that is likely not the case for other users.

**Comment by u8sand** [comment]
Addressed in #138 
Thanks again
